@host_address = http://localhost:5001

### Create supervisor employee
# @name create_supervisor_employee
POST {{host_address}}/api/employees
Content-Type: application/json

{
  "firstName": "Joe",
  "lastName": "Doe",
  "email": "j.doe@gmail.com",
  "supervisorId": null
}

###
@supervisor_id = {{create_supervisor_employee.response.body.$}}

###
GET http://localhost:8080/api/employees/{{supervisor_id}}

###
GET {{host_address}}/api/employees/{{supervisor_id}}

### Create Employee with Supervisor
# @name create_employee_with_supervisor
POST {{host_address}}/api/employees
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "supervisorId": "{{supervisor_id}}"
}

### Create Employee without Supervisor
# @name create_employee_without_supervisor
POST {{host_address}}/api/employees
Content-Type: application/json

{
  "firstName": "Jane",
  "lastName": "Smith",
  "supervisorId": null
}

###
@employee_without_supervisor_id = {{create_employee_without_supervisor.response.body.$}}


### Assign Supervisor to Employee
PATCH {{host_address}}/api/employees/{{employee_without_supervisor_id}}/supervisors/{{supervisor_id}}

### Delete Employee
DELETE {{host_address}}/api/employees/{{employee_without_supervisor_id}}