<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
      <ProjectReference Include="..\chronos.shared.configuration\chronos.shared.configuration.csproj" />
      <ProjectReference Include="..\chronos.shared.messaging\chronos.shared.messaging.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="RabbitMQ.Client" Version="7.2.0" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
