services:
  chronos-mongo:
    image: mongo
    container_name: chronos_env_mongo
    restart: unless-stopped
    volumes:
      - chronos-mongo:/data/db
    ports:
      - 10011:27017
    networks:
      - chronos-network

  chronos-rabbitmq:
    build:
      context: ../rabbitmq
      dockerfile: Dockerfile
    container_name: chronos_env_rabbitmq
    restart: unless-stopped
    volumes:
      - chronos-rabbitmq:/var/lib/rabbitmq
    networks:
      - chronos-network
    ports:
      - 10012:5672
      - 10013:15672

  chronos-postgres:
    image: postgres:17
    container_name: chronos_env_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: chronos
      POSTGRES_PASSWORD: chronos
      POSTGRES_DB: chronos
    volumes:
      - chronos-postgres:/var/lib/postgresql/data
    ports:
      - 10014:5432
    networks:
      - chronos-network

volumes:
  chronos-mongo:
    driver: local
  chronos-rabbitmq:
    driver: local
  chronos-postgres:
    driver: local

networks:
  chronos-network:
    driver: bridge