#!/bin/bash

ENV="docker"
EMPLOYEES_SVC="chronos-employees"
CONTRACTS_SVC="chronos-contracts"
TIME_LOGS_SVC="chronos-time-logs"
TIME_REPORTS_SVC="chronos-time-reports"
NOTIFICATIONS_SVC="chronos-notifications"
SVC_PREFIX="chronos_svc"

# Shared
MONGO_CONNECTION_STRING="mongodb://chronos_env_mongo:27017"
POSTGRES_HOST="chronos_env_postgres"
POSTGRES_PORT="5432"
POSTGRES_USERNAME="chronos"
POSTGRES_PASSWORD="chronos"
RABBIT_MQ_HOSTNAME="chronos_env_rabbitmq"
RABBIT_MQ_PORT="5672"
RABBIT_MQ_USERNAME="admin"
RABBIT_MQ_PASSWORD="123456"
RABBIT_MQ_VIRTUAL_HOST="chronos"

export DOTNET_ENVIRONMENT="${ENV}"

# Employees
export EMPLOYEES_DAL_OPTIONS_CONNECTION_STRING="${MONGO_CONNECTION_STRING}"
export EMPLOYEES_DAL_OPTIONS_DATABASE_NAME="${EMPLOYEES_SVC}_${ENV}"
export EMPLOYEES_RABBIT_MQ_HOSTNAME="${RABBIT_MQ_HOSTNAME}"
export EMPLOYEES_RABBIT_MQ_PORT="${RABBIT_MQ_PORT}"
export EMPLOYEES_RABBIT_MQ_USERNAME="${RABBIT_MQ_USERNAME}"
export EMPLOYEES_RABBIT_MQ_PASSWORD="${RABBIT_MQ_PASSWORD}"
export EMPLOYEES_RABBIT_MQ_VIRTUAL_HOST="${RABBIT_MQ_VIRTUAL_HOST}"
export EMPLOYEES_OUTBOX_CONNECTION_STRING="Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=chronos_employees;Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD}"

# Contracts
export CONTRACTS_DAL_OPTIONS_CONNECTION_STRING="${MONGO_CONNECTION_STRING}"
export CONTRACTS_DAL_OPTIONS_DATABASE_NAME="${CONTRACTS_SVC}_${ENV}"
export CONTRACTS_RABBIT_MQ_HOSTNAME="${RABBIT_MQ_HOSTNAME}"
export CONTRACTS_RABBIT_MQ_PORT="${RABBIT_MQ_PORT}"
export CONTRACTS_RABBIT_MQ_USERNAME="${RABBIT_MQ_USERNAME}"
export CONTRACTS_RABBIT_MQ_PASSWORD="${RABBIT_MQ_PASSWORD}"
export CONTRACTS_RABBIT_MQ_VIRTUAL_HOST="${RABBIT_MQ_VIRTUAL_HOST}"
export CONTRACTS_HTTP_EMPLOYEE_OPTIONS_URL="http://chronos_svc_employees:8080"
export CONTRACTS_OUTBOX_CONNECTION_STRING="Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=chronos_contracts;Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD}"

# Time Logs
export TIME_LOGS_DAL_OPTIONS_CONNECTION_STRING="${MONGO_CONNECTION_STRING}"
export TIME_LOGS_DAL_OPTIONS_DATABASE_NAME="${TIME_LOGS_SVC}_${ENV}"
export TIME_LOGS_RABBIT_MQ_HOSTNAME="${RABBIT_MQ_HOSTNAME}"
export TIME_LOGS_RABBIT_MQ_PORT="${RABBIT_MQ_PORT}"
export TIME_LOGS_RABBIT_MQ_USERNAME="${RABBIT_MQ_USERNAME}"
export TIME_LOGS_RABBIT_MQ_PASSWORD="${RABBIT_MQ_PASSWORD}"
export TIME_LOGS_RABBIT_MQ_VIRTUAL_HOST="${RABBIT_MQ_VIRTUAL_HOST}"
export TIME_LOGS_HTTP_COMMUNICATION_OPTIONS_ENABLED="true"
export TIME_LOGS_OUTBOX_CONNECTION_STRING="Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=chronos_time_logs;Username=${POSTGRES_USERNAME};Password=${POSTGRES_PASSWORD}"

# export NOTIFICATIONS_KESTREL_HTTP_URL="http://0.0.0.0:8080"
# export NOTIFICATIONS_KESTREL_GRPC_URL="http://0.0.0.0:8081"
# export NOTIFICATIONS_DAL_OPTIONS_CONNECTION_STRING="mongodb://chronos_env_mongo:27017"
# export NOTIFICATIONS_DAL_OPTIONS_DATABASE_NAME="${NOTIFICATIONS_SVC}_${ENV}"
# export NOTIFICATIONS_GRPC_COMMUNICATION_OPTIONS_ENABLED="false"
# export NOTIFICATIONS_RABBIT_MQ_HOSTNAME="chronos_env_rabbitmq"
# export NOTIFICATIONS_RABBIT_MQ_PORT="5672"
# export NOTIFICATIONS_RABBIT_MQ_USERNAME="admin"
# export NOTIFICATIONS_RABBIT_MQ_PASSWORD="123456"
# export NOTIFICATIONS_RABBIT_MQ_VIRTUAL_HOST="chronos"

# export TIME_REPORTS_KESTREL_HTTP_URL="http://0.0.0.0:8080"
# export TIME_REPORTS_DAL_OPTIONS_CONNECTION_STRING="mongodb://chronos_env_mongo:27017"
# export TIME_REPORTS_DAL_OPTIONS_DATABASE_NAME="${TIME_REPORTS_SVC}_${ENV}"
# export TIME_REPORTS_RABBIT_MQ_HOSTNAME="chronos_env_rabbitmq"
# export TIME_REPORTS_RABBIT_MQ_PORT="5672"
# export TIME_REPORTS_RABBIT_MQ_USERNAME="admin"
# export TIME_REPORTS_RABBIT_MQ_PASSWORD="123456"
# export TIME_REPORTS_RABBIT_MQ_VIRTUAL_HOST="chronos"

WORKING_CONTAINERS=$(docker ps --filter "name=${SVC_PREFIX}" --format "{{.ID}}" | wc -l)

echo "Working containers: ${WORKING_CONTAINERS}"

if [ "$WORKING_CONTAINERS" -ne 0 ]; then
    docker stop $(docker ps --filter "name=${SVC_PREFIX}" --format "{{.ID}}")
fi

ALL_CONTAINERS=$(docker ps -a --filter "name=${SVC_PREFIX}" --format "{{.ID}}"  | wc -l)

echo "All chronos containers: ${ALL_CONTAINERS}"

if [ "$ALL_CONTAINERS" -ne 0 ]; then
    docker rm $(docker ps -a --filter "name=${SVC_PREFIX}" --format "{{.ID}}")
fi

docker-compose -f docker-compose-svc.yaml up -d