<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>chronos.notifications.core</RootNamespace>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Figgle" Version="0.6.5" />
      <PackageReference Include="Figgle.Fonts" Version="0.6.5" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.11" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.11" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.11" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.11" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.11" />
      <PackageReference Include="MongoDB.EntityFrameworkCore" Version="9.0.3" />
      <PackageReference Include="Ulid" Version="1.4.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\shared\chronos.shared.configuration\chronos.shared.configuration.csproj" />
      <ProjectReference Include="..\..\shared\chronos.shared.exceptions\chronos.shared.exceptions.csproj" />
      <ProjectReference Include="..\..\shared\chronos.shared.messaging.rabbit-mq\chronos.shared.messaging.rabbit-mq.csproj" />
    </ItemGroup>

</Project>
