apiVersion: v1
kind: Secret
metadata: 
  name: secrets
  namespace: chronos-namespace
data: 
  dal-connection-string: "bW9uZ29kYjovL21vbmdvLmNocm9ub3MtbmFtZXNwYWNlLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3"
  rabbitmq-password: "MTIzNDU2"