<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>chronos.employees.core</RootNamespace>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="9.0.11" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.11" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.11" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.11" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.11" />
      <PackageReference Include="MongoDB.EntityFrameworkCore" Version="9.0.3" />
      <PackageReference Include="Scrutor" Version="5.0.1" />
      <PackageReference Include="Ulid" Version="1.4.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\shared\chronos.shared.configuration\chronos.shared.configuration.csproj" />
      <ProjectReference Include="..\..\shared\chronos.shared.exceptions\chronos.shared.exceptions.csproj" />
      <ProjectReference Include="..\..\shared\chronos.shared.kernel\chronos.shared.kernel.csproj" />
      <ProjectReference Include="..\..\shared\chronos.shared.messaging.outbox\chronos.shared.messaging.outbox.csproj" />
      <ProjectReference Include="..\..\shared\chronos.shared.messaging.rabbit-mq\chronos.shared.messaging.rabbit-mq.csproj" />
      <ProjectReference Include="..\..\shared\chronos.shared.messaging\chronos.shared.messaging.csproj" />
    </ItemGroup>

</Project>
