<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>chronos.employees.core</RootNamespace>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.10" />
      <PackageReference Include="MongoDB.EntityFrameworkCore" Version="9.0.3" />
      <PackageReference Include="Ulid" Version="1.4.1" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Communication/Sync/Grpc/Protos/employees.proto" GrpcServices="Server" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\shared\chronos.shared.configuration\chronos.shared.configuration.csproj" />
    </ItemGroup>

</Project>
