services:
  chronos-mongo:
    image: mongo
    container_name: chronos-mongo
    restart: unless-stopped
    volumes:
      - chronos-mongo:/data/db
    ports:
      - 10011:27017
    networks:
      - chronos-network

volumes:
  chronos-mongo:
    driver: local

networks:
  chronos-network:
    driver: bridge