#docker_configuration
# @employees_host = http://localhost:11001/api

#IDE_configuration
# @employees_host = http://localhost:5001/api
# @time_loggers_host = http://localhost:5002/api

@employees_host = http://localhost:5005

### Scenario: Create Employee and Time Logger

### Step 1: Create Employee
# @name create_employee
POST {{employees_host}}/employees
Content-Type: application/json

{
  "firstName": "Johnnie",
  "lastName": "Doe",
  "email":"jdchronos.com",
  "supervisorId": null
}

###
@employee_id = {{create_employee.response.body.$}}

### Step 3: Get Employee Details
GET {{employees_host}}/employees

### Step 3: Get Employee Details
GET {{employees_host}}/employees/{{employee_id}}
