# creating deployment for employees app
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronos-employees-deployment
  namespace: chronos-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronos-employees
  template:
    metadata:
      labels:
        app: chronos-employees
    spec:
      containers:
        - name: chronos-employees
          image: chronos-employees:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: appsettings-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
      volumes:
        - name: appsettings-volume
          secret:
            secretName: chronos-employees-secret
            defaultMode: 0600 # 0644 is default
            items:
              - key: appsettings.json
                path: appsettings.json
---

apiVersion: v1
kind: Secret
metadata: 
  name: chronos-employees-secret
  namespace: chronos-namespace
  labels:
    app: chronos-employees
type: Opaque
data:
  appsettings.json: |
    ICB7CiAgICAgICJBcHBPcHRpb25zIjogewogICAgICAgICJOYW1lIjogIkNocm9ub3MgRW1wbG95ZWVzIDEiCiAgICAgIH0sCiAgICAgICJEYWxPcHRpb25zIjogewogICAgICAgICJDb25uZWN0aW9uU3RyaW5nIjogIm1vbmdvZGI6Ly9sb2NhbGhvc3Q6MzAwMDEiLAogICAgICAgICJEYXRhYmFzZU5hbWUiOiAiQ2hyb25vcy1FbXBsb3llZXMiCiAgICAgIH0sCiAgICAgICJHcnBjQ29tbXVuaWNhdGlvbk9wdGlvbnMiOiB7CiAgICAgICAgIkVuYWJsZWQiOiBmYWxzZQogICAgICB9CiAgICB9